# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NasaViewer
  pod 'Alamofire', '~> 5.2'
  target 'NasaViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NasaViewerUITests' do
    # Pods for testing
  end

end
